markdown: kramdown
optional_front_matter:
  enabled: true

include:
  - README.md

defaults:
  - scope:
      path: "README.md"
      type: "pages"
    values:
      layout: "page"
      permalink: /README.md
      title: BOOKS
  - scope:
      path: "ABOUT.md"
      type: "pages"
    values:
      layout: "page"
      permalink: /ABOUT.md
      title: ABOUT
  - scope:
      path: "USAGE.md"
      type: "pages"
    values:
      layout: "page"
      permalink: /USAGE.md
      title: USAGE
